version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /fecal_analyzer_server_server/
    destination: /home/ec2-user/serverpod/upload/fecal_analyzer_server_server/
hooks:
  BeforeInstall:
    - location: fecal_analyzer_server_server/deploy/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: fecal_analyzer_server_server/deploy/aws/scripts/start_server
      timeout: 300
      runas: root
